MapFrame fix and zoom to layer enhancements
+[Enhancement] Added buffer_factor on Map.zoom_to_layer and Map.set_extent to control space around layers and extents.
+[Fix] Fixed regression in Map.find_layer where providing a layer name would give "AttributeError: 'Layer' object has no attribute 'dataSource'"
+[Fix] Maps were being incompletely assigned to map frames in certain instances, causing inability to use zoom_to_layer, and anything that cross-references maps and frames. Fixed.